name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Alternative: 'zulu', 'corretto'
          java-version: '23'  # Change to match your project

      - name: Set Up Chrome and Firefox
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable firefox

      - name: Set Up ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROME_DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -q -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip"
          sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Set Up GeckoDriver (For Firefox)
        run: |
          GECKO_DRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.tag_name')
          wget -q -O /tmp/geckodriver.tar.gz "https://github.com/mozilla/geckodriver/releases/download/${GECKO_DRIVER_VERSION}/geckodriver-${GECKO_DRIVER_VERSION}-linux64.tar.gz"
          sudo tar -xzf /tmp/geckodriver.tar.gz -C /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver

      - name: Verify Chrome & Firefox Installation
        run: |
          google-chrome --version
          chromedriver --version
          firefox --version
          geckodriver --version

      - name: Build and Run Tests
        run: mvn clean test
          - name: Upload Test Reports
        if: always()  # Ensures reports are uploaded even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: target/reports/
