name: Selenium with TestNG - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Build and Run Tests
        run: mvn clean test
      - name: Upload Test Reports
        if: always()  # Ensures reports are uploaded even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: target/reports/*
