name: Run Tests with Extent Reports

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the project
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Upload Extent Report
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: target/reports/  # Adjust this path based on your Extent Report output directory
